### ISSUE TITLE
build failed, 

### ISSUE THREAD

**Issue by zhangn1985** [sbwtw/libpurple-rust#1]
```
Adding include dir: /usr/include/glib-2.0
Adding include dir: /usr/lib/x86_64-linux-gnu/glib-2.0/include
Adding include dir: /usr/include/libpurple
/usr/include/glib-2.0/glib/gmacros.h:38:10: fatal error: 'stddef.h' file not found, err: true

--- stderr
/usr/include/glib-2.0/glib/gmacros.h:38:10: fatal error: 'stddef.h' file not found
thread 'main' panicked at 'Bindings generation failed', /home/ning/.cargo/registry/src/github.com-1ecc6299db9ec823/purple-sys-0.1.0/build.rs:47:13
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print

```
OS debian9

has to add: 
    bindings = bindings.clang_arg("-I").clang_arg("/usr/include/clang/3.8/include");

to pass build

same issue with clang 5.0

**Comment by sbwtw** [comment]
Thanks, will fix it later

**Comment by lupine** [comment]
I bumped into this problem myself. I only had `libclang1-7` installed on my Debian Buster machine, no `clang`.

I found that by installing `clang` alongside, the build managed to pick up the headers. No idea why :D.

**Comment by abhijeetbhagat** [comment]
> 
> 
> I bumped into this problem myself. I only had `libclang1-7` installed on my Debian Buster machine, no `clang`.
> 
> I found that by installing `clang` alongside, the build managed to pick up the headers. No idea why :D.

thanks! installed `clang` and this fix the problem building rust-libnice.
